# Generated by Django 4.1 on 2023-09-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
