# Generated by Django 4.1 on 2023-10-23 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
